package fun.rich.display.screens.clickgui.components.implement.module;

import fun.rich.features.module.Module;
import fun.rich.features.impl.combat.*;
import fun.rich.features.impl.misc.*;
import fun.rich.features.impl.movement.*;
import fun.rich.features.impl.player.*;
import fun.rich.features.impl.render.*;


public class ModuleDescriptions {
    public static String getDescription(Module module) {
        if (module instanceof ServerHelper) return "Помогает взаимодействовать с сервером, предоставляя полезные функции.";
        if (module instanceof WaterSpeed) return "Увеличивает скорость передвижения в воде.";
        if (module instanceof ItemScroller) return "Настраивает поведение предметов для удобства.";
        if (module instanceof Hud) return "Отображает дополнительную информацию на экране.";
        if (module instanceof AuctionHelper) return "Помогает управлять аукционами на сервере.";
        if (module instanceof ProjectilePrediction) return "Предсказывает траекторию полета снарядов.";
        if (module instanceof AntiAFK) return "Выполняет какое-то действие чтобы игрока не кикнуло за афк.";
        if (module instanceof Strafe) return "Помогает игроку при ходьбе.";
        if (module instanceof TargetStrafe) return "Крутится вокруг таргета в aura.";
        if (module instanceof Jesus) return "Дает возможность игроку ходить по воде.";
        if (module instanceof ProjectileHelper) return "Помогает игроку наводится на цель.";
        if (module instanceof XRay) return "Позволяет видеть сквозь блоки для поиска ресурсов.";
        if (module instanceof TriggerBot) return "Бьет сущность если игрок смотрит на нее.";
        if (module instanceof Aura) return "Автоматически атакует ближайших врагов.";
        if (module instanceof AutoSwap) return "Автоматически меняет предметы в руке.";
        if (module instanceof AutoPilot) return "Наводит камеру игрока на ценный предмет сервера ReallyWorld";
        if (module instanceof NoFriendDamage) return "Предотвращает урон по союзникам.";
        if (module instanceof SelfDestruct) return "Скрывает чит с игры, находится в разработке.";
        if (module instanceof AutoBuy) return "Автоматически скупает ресурсы с аукциона.";
        if (module instanceof HitBoxModule) return "Изменяет размер хитбоксов сущностей.";
        if (module instanceof AntiBot) return "Обнаруживает и игнорирует ботов на сервере.";
        if (module instanceof AutoCrystal) return "Автоматизирует размещение и уничтожение кристаллов.";
        if (module instanceof AutoSprint) return "Автоматически включает спринт при движении.";
        if (module instanceof NoPush) return "Предотвращает отталкивание игроков и сущностей.";
        if (module instanceof ElytraHelper) return "Улучшает управление элитрами.";
        if (module instanceof JoinerHelper) return "Облегчает процесс входа на сервер.";
        if (module instanceof NoDelay) return "Убирает задержки при выполнении действий.";
        if (module instanceof Velocity) return "Уменьшает отбрасывание от атак.";
        if (module instanceof AutoRespawn) return "Автоматически возрождает игрока после смерти.";
        if (module instanceof NoSlow) return "Устраняет замедление при определенных действиях.";
        if (module instanceof InventoryMove) return "Позволяет двигаться при открытом интерфейсе.";
        if (module instanceof Blink) return "Создает иллюзию телепортации для других игроков.";
        if (module instanceof AutoTool) return "Автоматически выбирает подходящий инструмент.";
        if (module instanceof Fly) return "Позволяет летать в режиме выживания.";
        if (module instanceof FastBreak) return "Ускоряет разрушение блоков.";
        if (module instanceof CameraSettings) return "Настраивает поведение камеры игрока.";
        if (module instanceof BlockOverlay) return "Подсвечивает блоки для лучшей видимости.";
        if (module instanceof Esp) return "Показывает местоположение сущностей через стены.";
        if (module instanceof AutoTotem) return "Автоматически использует тотемы бессмертия.";
        if (module instanceof EnderChestPlus) return "Улучшает функционал эндер-сундука.";
        if (module instanceof FreeCam) return "Предоставляет инструменты для отладки камеры.";
        if (module instanceof ChestStealer) return "Быстро забирает предметы из контейнеров.";
        if (module instanceof AutoTpAccept) return "Автоматически принимает запросы на телепортацию.";
        if (module instanceof Arrows) return "Стрелочки.";
        if (module instanceof AutoLeave) return "Автоматически покидает сервер при угрозе.";
        if (module instanceof WorldTweaks) return "Настраивает параметры мира для удобства.";
        if (module instanceof NoClip) return "Позволяет проходить сквозь блоки.";
        if (module instanceof NoRender) return "Отключает рендеринг определенных объектов.";
        if (module instanceof TargetPearl) return "Автоматически бросает жемчужины в цель.";
        if (module instanceof NameProtect) return "Скрывает имена игроков для защиты.";
        if (module instanceof SeeInvisible) return "Позволяет видеть невидимых игроков.";
        if (module instanceof AutoArmor) return "Автоматически надевает лучшую броню.";
        if (module instanceof AutoUse) return "Автоматически использует предметы.";
        if (module instanceof NoInteract) return "Блокирует взаимодействие с объектами.";
        if (module instanceof CrossHair) return "Настраивает отображение прицела.";
        if (module instanceof SuperFireWork) return "Усиливает фейерверки для полета.";
        if (module instanceof Spider) return "Позволяет взбираться по стенам как паук.";
        if (module instanceof ServerRPSpoofer) return "Подделывает данные для серверов.";
        if (module instanceof LongJump) return "Длинные прыжки, эквивалент HighJump.";
        if (module instanceof ShiftTap) return "Автоматически приседает при ударе.";
        if (module instanceof AspectRatio) return "Изменяет соотношение сторон экрана.";
        if (module instanceof FreeLook) return "Позволяет свободно вращать камеру без движения игрока.";
        if (module instanceof ClickPearl) return "Автоматически использует жемчужины при клике.";
        if (module instanceof ClickFriend) return "Добавляет игроков в список друзей по клику.";
        if (module instanceof WindJump) return "Усиливает прыжки с учетом направления ветра.";
        if (module instanceof TargetESP) return "Подсвечивает цели для лучшей видимости.";
        if (module instanceof NoWeb) return "Позволяет двигаться через паутину без замедления.";
        if (module instanceof IRC) return "Встроенный чат для общения.";
        if (module instanceof Speed) return "Увеличивает скорость передвижения игрока.";
        if (module instanceof SwingAnimation) return "Настраивает анимацию взмаха руки.";
        if (module instanceof ViewModel) return "Изменяет отображение модели предметов в руке.";
        if (module instanceof AirStuck) return "Фризит игрока в воздухе, предотвращая движение.";
        if (module instanceof NoFallDamage) return "Предотвращает получение урона от падения.";
        if (module instanceof ElytraMotion) return "Улучшает управление и скорость полета на элитрах.";
        if (module instanceof WorldParticles) return "Добавляет или изменяет частицы в мире для визуального эффекта.";
        if (module instanceof BlockESP) return "Подсвечивает определенные блоки через стены.";
        if (module instanceof KillEffect) return "Добавляет визуальные эффекты при убийстве.";
        if (module instanceof JumpCircle) return "Красивые круги после прыжка.";
        if (module instanceof Cosmetic) return "Косметические визуальные эффекты и внешний вид.";
        return "Описание модуля отсутствует.";
    }
}